### ISSUE TITLE
Add item on character sheet doesnt work

### ISSUE THREAD

**Issue by Hammundr** [Gerdofal/foundryvtt-cyberpunkred#25]
Unsure if its a browser issue, or something else, but the add item button doesnt work on the Cyberware, Weapons and Gear tabs. 

If that could be fixed i will be able to start my homebrew Red/2020 game! Thanks guys!

**Comment by Gerdofal** [comment]
Thank you!  Known issue. Current public version doesn’t yet include full item support. The next version, currently in dev, will. I’m working now on a system which allows items to automatically modify rolls.  Back end code is fully completed. Just working on UI elements. Hopefully out in a week!

You can follow changes here: https://github.com/Gerdofal/foundryvtt-cyberpunkred/blob/development/releasenotes.md

**Comment by Hammundr** [comment]
The Character sheet is not massivly useful without the ability to store weapons and gear. Could you add some text areas to the sheet to manually type stuff in as a temporary/short term solution? 

Appreciate you want to have all the stats auto update, but this small change would allow my group to start with Foundry - what better way to playtest your game system? :)

**Comment by Gerdofal** [comment]
Weapons are already available on the combat setup tab (make sure you have simple combat setup active in options) there is space for ten weapons with corresponding damage and attack buttons on the combat tab. 

A text box for other gear is a good idea. I’ll add that into the next build.

**Comment by Hammundr** [comment]
That will be awesome! Thanks :)

**Comment by Hammundr** [comment]
I had a little play this morning and have come up with the following, unsure if its something you might want to consider for the character sheet. Its a little 'rough and ready'

Changes;
1. Replaced Itemlist with Text area in Cyberware, Weapons and Gear tabs (Based off the Bio code)
2. Added Basic Armour value to the combat sheet (based off the Health/Luck code)

Appreciate there maybe better ways to do this, but these couple of changes give me all i need to get playing CPR in Foundry, so i thought i would share - sorry i'm not too familiar with Git so ive dropped the updated files directly here (Git n00b!)

[Updates.zip](https://github.com/Gerdofal/foundryvtt-cyberpunkred/files/4840384/Updates.zip)

**Comment by Gerdofal** [comment]
oops, you're right. forgot armor :) thanks

**Comment by Hammundr** [comment]
No Problem, hope you like what ive done for that :)

**Comment by Gerdofal** [comment]
I like your idea for the armor. I'm going to use part of that.

The "combat!" tab is getting a bit too long, so the armor that you listed is going to "combat setup". I like the buttons you have for add and subtract armor. I'm thinking about that. There is some need for that, but also a need to support the armor stacking rules from CP2020 and that requires separate armor slots that are defined by a specific order. (innermost armor, next out, next out..... and finally cover armor) Thoughts?

The inventory tabs you created are actually is going to get one tab.... "Text Inventory" if I can fit that name The reason for that is that I already have the item based inventory tabs done on the dev source, just haven't pushed it live yet.

**Comment by Gerdofal** [comment]
Oh, take a look at template.json to get an idea of how I'm constructing the data model for the actor. It will give you a sense of how I'm nesting things. The gear text inventory is going to go into data.description.textinventory because that's used on both characters and NPCs

**Comment by Hammundr** [comment]
I'll check that out, thanks - some of the edits i made were rudimentary just to get us going, i do like the idea of the cyberware page having modifiers etc. The Items section sounds good, i'm looking forward to trying that out when your ready.

I've got my first Foundry game of CPR this thursday, so i'll feedback anything my players pick up :)

**Comment by Gerdofal** [comment]
By the way, the push I just did to the to the dev branch is working. If you want to manually install it, you are welcome to. I'm going to try to release it tonight if I can, but I have some localization that isn't completed yet so the release may be delayed a day or two.

**Comment by Gerdofal** [comment]
...I should add there is quite a bit of bug checking to go to :)

**Comment by Hammundr** [comment]
happy to help out hunting down and squashing bugs - i'm not the greatest dev but im happy to have a go :)

**Comment by Hammundr** [comment]
One bug i am having - not sure if its something ive introduced with my local changes - but Character Role doesnt seem to be saving, if i find it i will let you know

**Comment by Gerdofal** [comment]
I have pushed version .31, it should be available now.

**Comment by Gerdofal** [comment]
The character role issue is fixed as well :)

**Comment by Gerdofal** [comment]
Here is a discord invite to a channel for suggestions for the sheet: https://discord.gg/5ZzpbYK
