### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jbhaywood** [Gerdofal/foundryvtt-cyberpunkred#32]
Not technically an issue, but I thought I'd offer some feedback after using this system for upcoming Cyberpunk RED game. First off, I'm so happy this exists. Thanks for making it.

First bit of feedback is around creating new characters. I had to make a bunch of them, mainly based off the pregens in the starter kit. Starting all skills with a value of 5 meant that I had to zero out a number of them, and since the pregens only list the ones characters have, not the ones they don't, it meant that it wasn't obvious to know which ones didn't apply. So I started just zeroing them all out before entering anything. I finally figured out that I could hack my local copy of the system to start skill and abilities at zero, and that made it easier going forward. I also alphabetized the skills list, which matches how they're listed in the pregen sheets, and that made setting them up easier too. It also makes finding them on the Combat tab when it comes time to do a roll a bit easier.

I also figured out that I could hack the html/css files of the character sheet to make them a bit easier to use, from a UI perspective. I mostly just left aligned things and gave them a bit more space. I'm attaching a couple pictures to show you what I mean.

Anyway, thanks again for doing all the heavy lifting. I can submit a pull request or two if you want these changes. 

![image](https://user-images.githubusercontent.com/5131886/90274867-2fc04d00-de16-11ea-8f77-06a2199a51ac.png)
![image](https://user-images.githubusercontent.com/5131886/90275009-74e47f00-de16-11ea-9b42-af808797e6d5.png)

**Comment by Gerdofal** [comment]
Thanks so much! Your feedback is very timely, I'm working on UI elements now.

I've already made some changes to the settings page to make it easier to use. How does this look?

![image](https://user-images.githubusercontent.com/6471848/90279998-a8270e00-de16-11ea-9cf7-35a3155f4c8f.png)

I hadn't thought of left aligning the boxes. I agree, that makes it easier to read them. Feel free to put in a pull request for that and the changes to the sorting and defaults.

Thanks!

**Comment by jbhaywood** [comment]
I like the new wording. I'd say the only downside with toggle boxes like that is that it's not obvious that you can click on them. The coloring, and making different states by default, helps though. You could also change the wording a bit to make it even more clear. Something like, "Click the following settings to enable/disable them for this sheet:".

**Comment by Gerdofal** [comment]
I updated the translation for the settings section to say: You may set the following settings for this sheet (Click boxes to change):

**Comment by Gerdofal** [comment]
Just noticed, the order in the template has no impact on the order in the sheet if the sheet was made ahead of time. This will cause problems in the future, so I'm going to go ahead and put a sorting function in the .js to sort on open. That way future changes of the skill list will not cause issues.

**Comment by Gerdofal** [comment]
This sorting function should be live now. Please advise if it doesn't appear to work for you :)
