### ISSUE TITLE
Add true/false to weapon template to track if ammo tracking is needed for that item.

### ISSUE THREAD

**Issue by Gerdofal** [Gerdofal/foundryvtt-cyberpunkred#38]

**Comment by ScyllPoesis** [comment]
Additionally, would be great to have a section for what type of ammo it uses. This could be a dropdown of `None, M.Pistol, H.Pistol...`, and then down the line we can tie the reload action to inventory.

As an aside, I think it would be nice to have a list inventory in addition/above the manual text entry to keep track of types of ammo and have a place to keep track of ammo in attributes (for future scripting and action mentioned above). Similar to my pitch for role list in #68. 

And aside my aside, a small number input for cash on this new inventory page would be nice too, storing it in manual text feels weird somehow given how currency is usually handled in these virtual sheets, don't know why.

**Comment by ScyllPoesis** [comment]
I'm tripping over my own suggestions! I actually piggy-backed #59 with the ammo suggestion while talking about item details.

**Comment by njfox** [comment]
Is this closed via #83?

**Comment by Gerdofal** [comment]
Resolved by addition of "none" ammo type
