### ISSUE TITLE
Add Humanity/Empathy dynamics 

### ISSUE THREAD

**Issue by ScyllPoesis** [Gerdofal/foundryvtt-cyberpunkred#58]
Humanity and Empathy need to be dynamic, like hit points or luck. I.e. (current) out of (maximum).

Bonus for automatic change of current Empathy whenever humanity changes (dropping from 54 humanity to 49 should reduce current Empathy from 5 to 4).

**Comment by Gerdofal** [comment]
Will be in next version.  I haven't read that section of the book yet, how do they round?

**Comment by ScyllPoesis** [comment]
So at chargen your current and max humanity are set to EMP * 10. From then on, anytime your humanity drops or rises a tenth place, your current empathy drops or rises. This effectively means (and easier to explain) that your current empathy always equals the digit in the tenth place of your humanity.

Example as I understand it: you start at 70 HUM thanks to 7 EMP. You get some cyberware which reduces your humanity by 9. When your humanity drops to 69, the tenth-place has changed negatively, and so EMP drops one, to 6. The rest of the loss doesn't change that place, so you drop to 61 HUM without any further effect.

**Comment by Gerdofal** [comment]
I read some of the book last night. It looks like this might be more complex than I thought, with the GM able to assign humanity loss for what the character sees, for example.￼ I think what I might need to do is make a humanity tab, where a record of humanity lost for a character can be kept.￼ As it's something that will be around for the entirety of a character's existence, I'm not exactly comfortable with a simple minus one button. Also, since cyberware loss is a roll after character creation, I need a record of what was lost for an item. What are your thoughts?￼

**Comment by ScyllPoesis** [comment]
A journal of sorts would certainly be an interesting approach. I came at this with the initial step of just hitting parity with the physical character sheet, but this would certainly be a pretty nice improvement.

I don't think we need to make it too automatic though. As long as you have the link of `CURRENT_EMP = FLOOR(CURRENT_HUMANITY / 10)` then the humanity changes can be recorded manually just fine, it's not like it happens so frequently to be annoying (and these events are usually something relatively interesting). 

Ex. A party comes across a couple scavvs playing football with a civvies head, they each roll a d8 or something, minus maybe their COOL or WILL. Then they can record in the journal with a new entry:
```
Saw scavs being scavs | -2
```
The humanity journal can be a list of such entries, and the current humanity can just be a sum of starting value (EMP * 10) and the pluses and minuses there, that shows up on the main stat screen as a read-only attribute. This would serve my group way above and beyond.

**Comment by Gerdofal** [comment]
that;s the plan, just make a journal where people can add negatives manually, be they from cyberware or from something they see. Also allows them to add positives from therapy.

**Comment by Gerdofal** [comment]
Now have a very very messy page that stores and allows deletion of entries. Need to work on UI next

![image](https://user-images.githubusercontent.com/6471848/99365120-56ea4880-2863-11eb-9bb5-40205eafe8aa.png)

**Comment by Gerdofal** [comment]
UI now in usable format. Will stop here for 0.40 and add new functionality in 0.41

![image](https://user-images.githubusercontent.com/6471848/99431359-1e745a00-28b7-11eb-9aab-81d41c544434.png)

**Comment by All-Who-Wander** [comment]
Good job man, been watching these. It's exciting and the community will
love it!

**Comment by Gerdofal** [comment]
The next UI refresh of this will likely be in version .43
