### ISSUE TITLE
Add "rarity" to items

### ISSUE THREAD

**Issue by ScyllPoesis** [Gerdofal/foundryvtt-cyberpunkred#59]
Items have a market "rarity" based on the scarcity economy that not only determines price, but availability. 

My idea is to just change the current attributes to two fields: a drop-down with the different market rarities, and a price field that automatically changes when you set the rarity but can be overridden manually.

**Comment by ScyllPoesis** [comment]
Additionally, while going through the attributes tab, weapons need to have a concealable flag, as well as an ammo type (for later use of linking to reload function and an ammunition inventory section).

**Comment by Gerdofal** [comment]
Thanks!  These are fairly quick. Likely not in the next release, most likely the one after.

**Comment by Gerdofal** [comment]
I have changed the back-end data so rarity is saved as a text field. I haven't yet created a drop-down or the automation to set the cost automatically, will put that in the next version

**Comment by Gerdofal** [comment]
Moving to Version .43 as I don't have time to create this automation and want to get this out.
