### ISSUE TITLE
Implement proper roll mod system

### ISSUE THREAD

**Issue by ScyllPoesis** [Gerdofal/foundryvtt-cyberpunkred#60]
Items currently have a mods system for modifying rolls. Once the new rules have settled in and rolling is cleaned up further it would be nice to have this tied in for items/cyberware that give passive bonuses. Possibly can utilize the new Active Effects system that just recently got implemented.

**Comment by ScyllPoesis** [comment]
Related, but gear and cyberware both have a bug where when setting the mods will give you an empty list of skills/attribute unless the entity is on a character sheet. This makes it slightly less convenient as you have to set up the link whenever you give out or load up the item.

Weapons have a similar issue with selecting weapon skill, but I believe the weapon config is due for a fuller sweep with the new FNF full rules.

**Comment by Gerdofal** [comment]
I haven't read the book yet, so I'm not exactly sure what you mean about passive bonuses. Do you mean just re-write the current mod system to use the active effects introduced in 7.x, or are you talking about bonuses that aren't currently possible in the current system?

**Comment by ScyllPoesis** [comment]
Certain gear and lots of cyberware will give passive bonuses on use for a certain period of time, or on use. 

Reading a bit through the design, the current system should work fine (with the active on/off flag), as long as it applies nicely across items and cyberware (again, seems buggy/non-functional in cases). So this can just be a bugfix instead of a new feature while the more meaty parts get wrapped up.

**Comment by Gerdofal** [comment]
Removing bug label as the bug with the empty list has been resolved. Keeping issue open as more needs to be done in this area
