### ISSUE TITLE
Refactor NPC rollable tables on sheet

### ISSUE THREAD

**Issue by ScyllPoesis** [Gerdofal/foundryvtt-cyberpunkred#61]
I like the slimmed-down NPC sheet approach, but it would be useful if NPCs could have their stats rolled as PCs can, and maybe with an weapons section as well. The current manual settings still leaves somethings that needs to be dealt with tracked out-of-foundry (ammo being a big one, skills too) which is problematic.

Unifying it somewhat with the PC sheet in use, just with less depth, will also make it easier for GMs to run through I presume.

**Comment by Gerdofal** [comment]
I'm wondering, maybe I need three sheet types? Thoughts?  Character, NPC, and ... um,mm... grunt or GM quick tools, or something?

**Comment by ScyllPoesis** [comment]
Certainly possible. I've seen a couple other systems do those sort of swarm/mob sheets. Regardless I think the only functional point to ensure would be to be able to quickly roll or at least reference combat stats, so maybe the mobs could have the combat improvements suggested above (quick roll of attacks, ammo/armor management) but leave skill rolls manual to so you don't have to list the whole pot. (it's such a long list, a pain for UX)
