### ISSUE TITLE
Implement cyberware management/slot system

### ISSUE THREAD

**Issue by ScyllPoesis** [Gerdofal/foundryvtt-cyberpunkred#62]
Note: I understand this is a more major feature request than the functional work I expect to be focused on over the next couple weeks.

The official character does a well enough job of this, so I feel that the FVTT sheet can just replicate it; list out the available foundational cybernetics, and show a list with the number of options if checked. Dragging to the sheet will place it into a specified spot as an easy first draft, but eventually cyberware should have an attribute specifying location that allows the sheet to place it in the correct spot or throw an error if there aren't enough option slots. 

ex. Interface Plugs would have the `Slot` attribute set to `Neuralware`, and adding it to a sheet would require the Neuralware foundational cybernetic (Neural Link) checked. Fashionware/Internal Body/External Body naturally don't need a foundational but still respect option limits.

**Comment by Gerdofal** [comment]
Hrmmm. This is completely doable, I'll keep it in mind for the future! Neat idea.
