### ISSUE TITLE
Character sheet role section

### ISSUE THREAD

**Issue by ScyllPoesis** [Gerdofal/foundryvtt-cyberpunkred#68]
One of the last things missing on the character sheet is a place to specify which roles a character has levels in (multi-role is a thing). It would be useful to just have a panel listing each role and let the user plug in levels as they get them, as having the level for each role as an attribute will be useful for future automation.

I imagine that each role ability can have their own panel that shows up when `{Role_LVL} > 0`, so you don't have to go into options and enable something like the hacking panel.

**Comment by Gerdofal** [comment]
They have multi-roll?  Wow, I never considered that. Yes, I guess it means another tab. Sigh, getting a few too many tabs on this thing. Cyberpunk is complicated.

**Comment by ScyllPoesis** [comment]
Haha, yep! It sure is. I think it'll be manageable if we make the role tabs show up only when specc'd, and maybe we conflate the bio and appearance tabs into a multi-field panel, kind of like how 5E sheets have bio & background and a few other things on one `Background` panel.

This is especially true if trying to replicate the physical sheet, as we'll need a few text fields for lifepath results anyways.

**Comment by Gerdofal** [comment]
This is completed in basic form in 0.42, on the settings tab
