### ISSUE TITLE
Show inline attribute mod on skills

### ISSUE THREAD

**Issue by ScyllPoesis** [Gerdofal/foundryvtt-cyberpunkred#76]
I don't know if it's just a matter of taste or if it's worth another box in the skill list (a bit more horizontal space wouldn't kill me personally), but one thing I did find less-than-ideal while converting my group's PDF sheets to the new actor skill list is the way the skill mods are displayed.

For reference, the official sheet displays the level of the skill, the associated attribute mod, and then the sum (the total mod). The actor sheet conversely has a manual mod (input) and item mod (display) field, but no attribute mod, which can lead to some misleading glances. Given the need to scroll just writing out the attribute is not wholly useful (Was my REF the 6 or 7 stat?), and even if you don't have training in autofire, an 8 REF will still give you a much better chance at things than the zero displayed gives you. 

My suggestion is either to simply add another auto-calculated (display) field before the total that just pulls the associated attribute down to the line, and sums it into the total field for a better picture of what your total mod actually is. I think there is reasonable space still left to squeeze in another box.

**Comment by Gerdofal** [comment]
Hmmm. Good idea. I think I can fit in another column there without going too wide. I can shrink the other boxes a little if I must.

**Comment by Gerdofal** [comment]
This is done in version .42 - The total displayed in skills is the total of skill + attribute
